reliefcamp/urls.py
from django.contrib import admin
from django.urls import path, reverse, re_path
from django.conf.urls import url
from django.views.generic import TemplateView

from refegue import views


app_name = 'refegue'
urlpatterns = [	

	path('', views.HomePageView.as_view(), name = 'home'),
	path('request/', views.CreateRequest.as_view(), name = 'requestview'),
	path('req_success/', views.ReqSuccess.as_view(), name = 'req_successview'),
    path('collection_center/', views.CollectionCenterView.as_view(), name = 'collection_centers_view'),
    path('collection_centers/', TemplateView.as_view(template_name = 'refegue/collectioncenter_state_select.html'), name = 'collection_centers_district_select'),
    re_path(r'collection_centers/(?P<location>\w+)/$', views.CollectionCenterListView.as_view(), name = 'collection_centers_list'),

    path('volunteer/', views.RegisterVolunteer.as_view(), name = 'registerview'),
    path('volunteerdata/', views.volunteerdata, name= 'volunteerdata'),

    path('NGO/', views.RegisterNGO.as_view(), name = 'ngoregisterview'),
    path('ngoview/', views.ngo_list, name = 'ngoview'),
    path('NGO/download/', views.download_ngo_list, name = 'ngo_download_view'),

    path('requests/', views.request_list, name = 'requestlistview'),
    path('request_details/<int:request_id>', views.request_details, name = 'requestdetailsview'),

    path('contactus/', views.districtmanager_list, name='contactus'),

    path('reg_success/', views.RegSuccess.as_view(), name = 'reg_successview'),
    path('req_success/', views.ReqSuccess.as_view(), name = 'req_succesview'),
    path('district_nedds/', views.DistNeeds.as_view(), name = 'distNeedsview'),

    path('reg_contrib/', views.RegisterContributor.as_view(), name = 'reg_contribview'),
    path('contribview/', views.contributors, name = 'contribview'),
    path('contrib_success/', views.ContribSuccess.as_view(), name = 'contribsuccessview'),

    path('disclaimer/', views.DisclaimerPage.as_view(), name = 'disclaimer'),
    path('ieee/', views.AboutIEEE.as_view(), name = 'aboutieee'),
    
    path('pcamp/', views.pcamplist, name = 'privatecamplist'),
    path('pcampadd', views.RegisterPrivateReliefCamp.as_view(), name = 'Private Camps'),
    path('pcampdet/', views.pcampdetails, name = 'privatecampdetails'),
    path('privatecc/', views.privatecc, name = 'privatedetials'),

    path('error/', views.error, name = 'errorview'),

    path('admin/', admin.site.urls),
]

refegue/models.py
import os
import uuid
from enum import Enum 

from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


divisions = (
	('dha', 'Dhaka'),
	('Cht', 'Chittagong'),
	('raj', 'Rajshai'),
	('bri', 'Barishal'),
	('khu', 'Khulna'),
	('syh', 'Sylhet'),
	('ran', 'Rangpur'),
	('mym', 'Mymensingh'),
)

districts = (
		('bar', 'Barguna'),
		('bri', 'Barisal'),
		('bhl', 'Bhola'),
		('jhl', 'Jhalokati'),
		('pat', 'Patuakhali'),
		('pir', 'Pirojpur'),
		('ban', 'Bandarban'),
		('bhm', 'Brahmanbaria'),
		('chd', 'Chandpur'),
		('cht', 'Chittagong'),
		('com', 'Comilla'),
		('cox', 'Cox\'s Bazar'),
		('fen', 'Feni'),
		('khg', 'Khagrachhari'),
		('lkh', 'Lakshmipur'),
		('nkh', 'Noakhali'),
		('rgm', 'Rangamati'),
		('dhk', 'Dhaka'),
		('frd', 'Faridpur'),
		('gaz', 'Gazipur'),
		('gop', 'Gopalganj'),
		('kis', 'Kishoreganj'),
		('mad', 'Madaripur'),
		('man', 'Manikganj'),
		('mun', 'Munshiganj'),
		('nar', 'Narayanganj'),
		('nas', 'Narsingdi'),
		('raj', 'Rajbari'),
		('sha', 'Shariatpur'),
		('tan', 'Tangail'),
		('bag', 'Bagerhat'),
		('chu', 'Chuadanga'),
		('jes', 'Jessore'),
		('jhe', 'Jhenaidah'),
		('khu', 'Khulna'),
		('kus', 'Kushtai'),
		('mag', 'Magura'),
		('meh', 'Meherpur'),
		('nri', 'Narail'),
		('sat', 'Satkhira'),
		('jam', 'Jamalpur'),
		('mym', 'Mymensingh'),

	)

status_type = (
	('new', 'New'),
	('pro', 'In progress'),
	('sup', 'Supplied'),
)

vol_categories = (
	('dcr', 'Doctor'),
	('hsv', 'Health Service'),
	('elw', 'Electrical Works'),
	('mew', 'Mechanical Works'),
	('cvw', 'Civil Works'),
	('plw', 'Plumbing works'),
	('vls', 'Vehical support'),
	('ckg', 'Cooking'),
	('rlo', 'relief operation'),
	('cln', 'Cleaning'),
	('bot', 'Boat Service'),
	('rck', 'Rock Climbing'),
	('oth', 'Others'),
)

contrib_status_types = (
	('new', 'New'),
	('ful', 'Fullfilled'),
)

relief_camp_status = (
	('active', 'Activate'),
	('closed', 'Closed'),
)

gender = (
	(0, 'Male'),
	(1, 'Female'),
	(2, 'Others'),
)

announcement_priorities = (
	('H', 'High'),
	('M', 'Medium'),
	('L', 'Low'))

person_status = (
	('new', 'New'),
	('checked_out', 'Checked Out'),
	('closed', 'Closed')
 )

contribution_type = (
	('food', 'Food'),
	('med', 'Medicines'),
	('shl', 'Shelter'),
	('clt', 'Clothing'),
	('sny', 'Sanitary materials'),
	('oth', 'Others')
)

class LSGTypes(Enum):	
	CORPORATION = 0
	MUNICIPALITY = 1
	GRAM_PANCHAYATH = 2


# Create your models here.
class Request(models.Model):
	
	division = models.CharField(
		max_length = 10,
		verbose_name = 'Division',
		choices = divisions,
		)

	district = models.CharField(
		max_length = 15, 
		verbose_name = 'District',
		choices = districts,
		)
	
	location = models.CharField( max_length = 500, verbose_name = 'Location')
	requestee = models.CharField(max_length = 100, verbose_name = 'Requestee')
	requestee_phone = models.CharField(max_length = 10, verbose_name = 'Requestee_phone')
	latlng = models.CharField(max_length = 100, verbose_name = 'GPS-Coordinate - GPS', blank= True)
	latlng_accuracy = models.CharField(max_length = 100, verbose_name = 'GPS-Accuracy', blank=True)

	# If it is enable no need to consider lat and lng

	is_request_for_others = models.BooleanField(verbose_name = 'Requesting for others-', default = False, help_text = 'If it is enabled, no need to consider lat and lng')

	needwater = models.BooleanField(verbose_name = 'Water')
	needfood = models.BooleanField(verbose_name = 'Food')
	needcloth = models.BooleanField(verbose_name = 'Cloth')
	needmed = models.BooleanField(verbose_name = 'Medicine')
	needtoilet = models.BooleanField(verbose_name = 'Toilet')
	needkit_utils = models.BooleanField(verbose_name = 'Kitchen Utilities')
	needrescue = models.BooleanField(verbose_name = 'Rescue')

	detailwater = models.CharField(max_length = 250, verbose_name = 'Detail for required water', blank = True)
	detailfood = models.CharField(max_length = 250, verbose_name = 'Detail for requird food', blank = True)
	detailcloth = models.CharField(max_length = 250, verbose_name = 'Detail for requird cloth', blank = True)
	detailmed = models.CharField(max_length = 250, verbose_name = 'Detail for required medicine', blank = True)
	detailtoilet = models.CharField(max_length = 250, verbose_name = 'Detail for required toilet', blank = True)
	detailkit_utils = models.CharField(max_length = 250, verbose_name = 'Detail for required kitchen utilities', blank = True)
	detailrescue = models.CharField(max_length = 250, verbose_name = 'Detail for required rescue', blank = True)

	needothers = models.CharField(max_length = 500, verbose_name = 'required others', blank = True)

	status = models.CharField(
		max_length = 10,
		choices = status_type,
		default = 'new'
		)
	supply_details = models.CharField(max_length = 10, blank = True)
	dateadd = models.DateTimeField(auto_now_add = True)


	def summarise(self):
		out = " "

		if (self.needwater):
			out += "water requirements :\n {}".format(self.detailwater)
		if (self.needfood):
			out += "food requirements :\n {}".format(self.detailfood)
		if (self.needcloth):
			out += "cloth requirements :\n {}".format(self.detailcloth)
		if (self.needmed):
			out += "medicine requirements :\n {}".format(self.detailmed)
		if (self.needtoilet):
			out += "toilet requirements :\n {}".format(self.detailtoilet)
		if (self.needkit_util):
			out += "Kitchen Utilities requirements :\n {}".format(self.detailkt_utils)
		if (self.needothers.strip() != 0):
			out += "\nOthers needs :\n {}".format(self.needothers)
		
		return out

	class Meta:
		verbose_name = 'Rescue: Request'
		verbose_name_plural = 'Rescue : Resquest'

	def __str__(self):
		return self.get_district_display()+' '+self.location


class Volunteer(models.Model):
	division = models.CharField(
		max_length = 10,
		verbose_name = 'Divisions',
		choices = divisions,
	)

	district = models.CharField(
		max_length = 15,
		verbose_name = 'districts',
		choices = districts,
	)

	name = models.CharField(max_length =100),
	phone_number_regex = RegexValidator(regex ='^((\+91|91|0)[\- ]{0, 1})?[456789]\d{9}$', message = 'Please enter 10 digitsmobile number or landline as 0 <std code><phone number>', code = 'invalid_mobile')
	phone = models.CharField(
		max_length = 10,
		verbose_name = 'Phone',
		validators = [RegexValidator(regex='^[6-9]\d{9}$', 
			message = "Please enter 10 digit mobile number", 
			code = 'invalid_mobile')]
	)

	organization = models.CharField(
		max_length = 250,
		verbose_name = 'Organization',
	)

	address = models.TextField(verbose_name = 'address')
	area = models.CharField(
		max_length = 15,
		verbose_name = 'Area of volunteering',
		choices = vol_categories,
	)
	is_spoc=models.BooleanField(default = False, verbose_name = 'Is point of Contact')
	joined = models.DateTimeField(auto_now_add = True)
	is_active = models.BooleanField(default = True)
	has_consented = models.BooleanField(default = False, verbose_name = 'Available')

	class Meta:
		verbose_name = 'Volunteer: individual'
		verbose_name_plural = 'Volunteer: individual'

	def __str__(self):
		return self.name

class NGO(models.Model):
	division = models.CharField(
		max_length = 10,
		verbose_name = 'divisions',
		choices = divisions,
	)
	district = models.CharField(
		max_length = 15, 
		verbose_name = 'districts',
		choices = districts,
	)
	organization = models.CharField(
		max_length = 250,
		verbose_name = 'Name of organization'
	)

	organization_type = models.CharField(max_length = 250, verbose_name = 'Type of Organization')
	organiation_address = models.TextField(default = '', verbose_name = 'Address of organization')
	name = models.CharField(max_length = 100, verbose_name = 'Contact person')
	phone_regex = RegexValidator(
		regex=r'^\+?1?\d{9, 15}$',
		message = 'Phone number must be entered in the format:"+999999999".upto 15 digits ')
	phone = models.CharField(validators=[phone_regex], max_length =17, blank= True)
	description = models.TextField(verbose_name = 'About organization')
	area = models.TextField(verbose_name = 'Area of volunteering')
	location = models.CharField(
		max_length = 500, 
		verbose_name = 'Preferred location to volunteer'
	)
	website_url = models.CharField(
		max_length=300, 
		verbose_name = "Enter your website link", 
		default = ''
	)
	is_spoc = models.BooleanField(default = False, verbose_name = 'Is point of Contact')
	joined = models.DateTimeField(auto_now_add= True)

	class Meta:
		verbose_name =  'Volunteer: NGO'
		verbose_name_plural = 'Volunteers: NGOs'

	def __str__(self):
		return self.name


class Contributor(models.Model):
	division = models.CharField(
		max_length = 10,
		verbose_name = 'Divisions',
		choices = divisions,
	)

	district = models.CharField(
		max_length = 15,
		verbose_name = 'Districts',
		choices = districts,
	)
	name = models.CharField(max_length = 100, verbose_name = 'Name')
	phone_number_regex = RegexValidator(regex='^((91|91|0)[\-]{0, 1})?[456789]\d{9}$', message = 'Please Enter 10 digits mobile number or landline as 0<std code><phone number>', code='invalid_mobile')
	phone = models.CharField(
		max_length = 14, 
		verbose_name = 'Phone -', 
		validators = [phone_number_regex], 
		)

	address = models.TextField(verbose_name = 'Address')
	contrib_details = models.TextField(verbose_name = 'Details of contribution Eg: 10 shirts', default ='')
	contribution_type = models.CharField(
		max_length = 3,
		choices = contribution_type,
		default = 'oth'
	)
	
	status = models.CharField(
		max_length = 10,
		choices = contrib_status_types, 
		default = 'new',
	)

	class Meta:
		verbose_name = 'Contributor:Donation'
		verbose_name_plural = 'Contributors:Donations'

	def __str__(self):
		return self.name + ' ' + self.get_district_display()


class DistrictManager(models.Model):
	district = models.CharField(
		max_length = 15,
		verbose_name = 'Districts',
		choices = districts,
	)

	name = models.CharField(max_length = 100, verbose_name = 'Name -')
	phone = models.CharField(max_length =11, verbose_name = 'phone')

refegue/templates/refegue/aboutieee.html
{% extends 'base.html' %}

{% block content %}

	<div class="row text-center static-page-box">
		<h1 class="text-center">About IEEE</h1>
		<p style="font-size: 1.7rem;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla nisi nihil quisquam cumque delectus nesciunt ut itaque animi.</p>
		<p style="font-size: 1.7rem;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla nisi nihil quisquam cumque delectus nesciunt ut itaque animi.</p>


	</div>

{% endblock content %}

refegue/templates/refegue/contrib_list.html
{% extends 'base.html' %}

{% block css %}

<style>
	.table{
		table-layout: fixed;
	}
	.table td{
		word-wrap: break-word;
	}

</style>
<style>
@media only screen and (max-width: 800px){
	#requests-table table, thead, tbody, th, td, tr{
		display: block;
	}
	#requests-table thead tr{
		position: absolute;
		top: -9999px;
		left: -9999px;
	}

	#requests-table tr{
		margin: 0 0 1rem 0;
	}

	#requests-table tr:nth-child(odd){
		background: #ccc;
	}

	#requests-table td{
		/*Behave like a 'row'*/
		border: none;
		border-bottom: 1px solid #eee;
		postion: relative;
		padding-left: 50%;
	}
	#requests-table td:before{
		/*Now like a table header*/
		position: absolute;
		/*top/left values mimic padding*/
		top: 0;
		left: 6px;
		width: 45%;
		padding-right: 10px;
		white-space: normal;
	}
	#requests-table td:nth-of-type(1):before{content: "Request Number -";}
	#requests-table td:nth-of-type(2):before{content: "district -";}
	#requests-table td:nth-of-type(3):before{content: "location ";}
	#requests-table td:nth-of-type(4):before{content: "Requestee ";}
	#requests-table td:nth-of-type(5):before{content: "Phone -";}
	#requests-table td:nth-of-type(6):before{content: "Date -";}
	#requests-table td:nth-of-type(7):before{content: "More details -";}
}
@media only screen and (max-width: 420px){
	#requests-table td {
	min-height: 60px;
	}
}
</style>
{% endblock css %}

{% block content %}
	<h1 class="text-center">Registered Contributor</h1>
	<h2 class="text-center">bangla language</h2>
	
	<form action="" method="get">
		{% bootstrap_form filter.form bound_css_class=False %}
		<input type="submit" class="btn btn-primary" value="View Contributor">
	</form>

	<div id="requests-table" class="table-responsive">
		<table id="req-table" class="table">
			<thead>
				<tr>
					<th>District</th>
					<th>Name</th>
					<th>Phone</th>
					<th>address -ml</th>
					<th>contrib_details -ml</th>
					<th>status -ml</th>
				</tr>
			</thead>
			<tbody>
				{% for req in data %}
				<tr>
					<td>{{ req.get_district_display }}</td>
					<td>{{ req.name }}</td>
					<td>{{ req.phone }}</td>
					<td>{{ req.address }}</td>
					<td>{{ req.contrib_details }}</td>
					<td>{{ req.get_status_display }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% include 'includes/pagination.html' %}



{% endblock content %}

refegue/templates/refegue/disclaimer.html
{% extends 'base.html' %}

{% block content %}

	<div class="row text-center static-page-box">
		<h1 class="text-center">Disclaimer</h1>
		<p style="font-size: 1.7rem">this portal has been developed for effective collaboration between various stakeholders such as citizen, Government authorities, various NGO and vulanteers, IEEE makes no represtations regarding the completeness, accuracy of any information and data contained on this portal or that such information received through the portal the requests receive does not warrant any commitment on the service. by the using site you acknowledge that you have read and agree to this </p>
		<b></b>
		<h1 class="text-center">GDPR</h1>
		<p style="font-style: 1.7rem;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe placeat accusantium laboriosam, consectetur repudiandae facilis blanditiis. Eaque?</p>
	</div>

{% endblock content %}

refegue/templates/refegue/district_needs.html
{% extends 'base.html' %} 

{% block breadcrumb %}
	<li class="breadcrumb-item"><a href="/">Home</a></li>
	<li class="breadcrumb-item active" aria-current="page">District Needs and Collection Centers</li>
{% endblock breadcrumb %}

{% block content %}
	<h1 class="text-center">District Needs &amp; Collection Center</h1>
	<h2 class="text-center">ban language</h2>
	<div class="">
		<table class="table">
			<tr>
				<th>District</th>
				<th>Items required</th>
				<th>Contents & collection points</th>
			</tr>
			{% for item in district_data %}
			<tr valign="top">
				<td><strong>{{ item.get_district_display }}</strong></td>
				<td>{{item.needs|linebreaks}}</td>
				<td>{{item.cnandpts|linebreaks}}</td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% endblock content %}

refegue/templates/refegue/districtmanager_list.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %}

	{% block breadcrumb %}
		<li class="breadcrumb-item"><a href="/">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">Contact Info</li>
	{% endblock breadcrumb %}


<h1 class="text-center">Contact Info</h1>
<h2 class="text-center">Lorem ipsum dolor sit amet.</h2>

<p class="text-center">
	Volunteers are available across the country. Contact the <u>District level point of Contacts</u> for any help <br>
</p>

<form action="" id="find-contact-info:get">
	{% bootstrap_form filter.form bound_css_class= Fasle %}

</form>
<div class="table-responsive">
	<table class="table">
		<tr>
			<th>Name - </th>
			<th>Phone- </th>
			<th>Other contacts</th>
		</tr>
		{% for req in filter.qs %}
		<tr>
			<td>{{ req.name }}</td>
			<td><a href="tel:{{ req.phone }}">{{ req.phone }}</a></td>	
			<td>{{ req.email }}</td>
		</tr>
		{% endfor %}
	</table>
</div>

<script>
	window.addEventListener('load', function(){
		$("#id_district").change(()=> {
			$("#find-contact-form").submit();
		})
		$('#id_district').selectize();
	});
</script>

{% endblock content %}

refegue/templates/refegue/request_details.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th colspan="2" style="text-align: center;">Request details for #{{ req.id }}</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><b>District: </b></td><td>{{ req.get_district_display }}</td>
				</tr>
				<tr>
					<td><b>Location: </b></td><td>{{ req.location }}</td>
				</tr>
				<tr>
					<td><b>GPS Location </b></td>
					<td>
						{% if req.latlng %}
							<a href="http://maps.google.com/?q={{ req.latlng}}" target="_blank" class="btn btn-sm btn-success">Open in maps</a><br>
							Accuracy: {{ req.latlng_accuracy }}
						{% else %}
							NA
						{% endif}
					</td>
				</tr>
				<tr>
					<td><b>Requestee: </b></td><td>{{ req.requestee }}</td>
				</tr>
				<tr>
					<td><b>Contact number</b></td>
					{% if req.is_old %}
						<td>Hidden for old requests</td>
					{% else %}
						<td><a href="tel:{{ req.requestee_phone}}"></a></td>
					{% endif %}
				</tr>
				<tr>
					<td><b>Summary of request:</b></td>{{ req.summarise|linebreaks<td></td>
				</tr>
				<tr>
					<td><b>Status of request:</b></td><td>{{req.get_status_display}}</td>
				</tr>
				<tr>
					<td><b>Date:</b></td><td>{{req.dateadded}}</td>
				</tr>

			</tbody>
		</table>
	</div>
	<h3 style="text-align: center;">Update</h3>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>Status</th>
					<th>Update Name</th>
					{% if user.is_authenticated %}
					<th>Update Phone</th>
					{% endif %}
					<th>Notes</th>
					<th>Update time</th>
				</tr>
			</thead>
			<tbody>
				{% for udpate in updates %}
				<tr>
					<td>{{ update.status }} {{ update.other_status }}</td>
					<td>{{ update.update_name }}</td>
					{% if user.is_authenticated %}
						<td>{{ update.update_phone }}</td>
					{% endif %}
					<td>{{ update.notes }}</td>
					<td>{{ update.update_ts }}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock content %}

refegue/templates/refegue/request_form.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% load static %}

{% block content %} 

<nav aria-label="breadcrumb">
	<ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="/">Home</a></li>
		<li class="breadcrumb-item active" aria-current="page">Request for help</li>
	</ol>
</nav>

<h1 class="text-center">Request for Help</h1>
<h2 class="text-center">Lorem ipsum dolor sit amet.</h2>

<form action="" method="post" class="simple-form">
	{% csrf_token %}
	{% bootstrap_form form %}

	<a href="" id="location-manually" class="btn btn-primary pull-right">
	Enter location manually</a>

	<div id="placepicker-form" style="display: none;">
		{% include 'refegue/placepicker_form.html' %}
	</div>
	
	<button type="submit" class="btn btn-primary">
		{% bootstrap_icon 'star' %} submit
	</button>
	
</form>
<!-- Instructions -->
<div id="instructionModal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" style="background:" white="">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
			<h3 id="myModalLabel">Allow Location - </h3>
		</div>
		<div class="modal-body">
			Lorem ipsum dolor sit amet. <br>
			1. Lorem ipsum dolor sit amet. <b>www.example.com whats to know your location</b> Lorem ipsum dolor sit amet. <br>
			2. Lorem ipsum dolor. <b>Allow</b>Lorem ipsum dolor sit amet. <br><br>

			How to allow location access <br><br>
			1. your browser will show a message <b>" www.example.com wants to know your location</b> <br> <br>
			2. Choose the option <b>Allow</b> Option
		</div>
		<div class="modal-footer">
			<button class="btn btn-primary" data-dismiss="modal_ok_button" aria-hidden="true">Ok</button>
		</div>
	</div>
</div>

<script type="text/javascript">
	try{
		window.addEventListener('load', checkVisibility, false);
		var checkboxes=document.querySelectorAll("input[type=checkbox]");
		for(var i=0; i<checkboxes.length; i++){
			checkboxes[i].addEventListener("Change", checkVisibility);
		}
		function checkVisibility(){
			var formgroups = document.querySelectorAll(".form-group");
			Array.protype.forEach.call(formgroups, function(e1, i){
				var checkbox=e1.querySelectorAll(".checkbox");
				if(checkbox.length>0){
					var checkboxElem = e1.querySelectorAll("input")[0]
					if (checkboxElem.id==="id_is_request_for_others"){
						if (checkboxElem.checked){
							$('#id_latlng_display').parrot().hide();
							$('#id_latlng_accuracy').parrot().hide();
						}
						else {
							$('#id_latlng_display').parrot().show();
							$('#id_latlng_accuracy').parrot.show();
						}
					}
				else if (checkboxElem.checked){
					formgroups[i+1].style.display='blank';
				}
				else {
					formgroups[i+1].style.display='none';
				}
				}
			});
		}
	}
catch(err){
	 console.log("Your browser does not allow some javascript programs.\nError Message:" + err.message)
}

window.addEventListener('load', function(){
	$('#id_district').selectize();
	$('#id_requestee_phone').attr('type', 'number');
	var gpsField=document.getElementById('id_latlng')
	var gpsAccuracyField = document.getElementById('id_latlng_accuracy');

	gpsField.readOnly = true;
	gpsAccuracyField.readOnly = true;

	var options = {
		enableHighAccuracy:true
	};
	var success = function(pos){
		var crd = pos.coords;
			gpsField.value = crd.latitude +","+crd.longitude;
			gpsAccuracyField.value = crd.accuracy+'Meters';
			$.get('https://nominatim.openstreetmap.org/reverse?format=json2&lat='+crd.latitude+'&lon='+crd.longitude+'&zoom=18&addressdetails=1')
			.done(function(response){
				var inputElem = $('<input class="form-control" id="id_latlng_display" readonly="true" value="'+response.display_name+'"</input>');
				$(gpsField.before(inputElem);
					$(gpsField).hide();
					console.log(response.display_name);
			})
				.fail(function(err){
					console.log(err);
				})
	}
	var error=function(err){
		console.warn('ERROR(${err.code}):${err.message}');
		showLocationPickerForm();
	}
	$('#instructionModal').on('hidden.bs.modal', function(e){
		navigator.geolocation.getCurrentPosition(success, error, options);
	})

	try{
		navigator.permissions.query({'name':geolocation}).then(
			function(result){
				switch(result.state){
					case 'prompt':$('#instructionModal').modal('show'); break;
					case 'granted':navigator.geolocation.getCurrentPosition(success, error, options); break;
				}
			})
	} 
	catch(err){
		//capture that don't have navigation or navigator.permissions
		$('#instructionModal').modal('show');
	}
});

function showLocationPickerForm(){
	$('#placepicker_form').show();
	$('#location-manually').hide();
}
$('#location-manually').on('click', function(event){
	event.preventDefault();
	showLocationPickerForm();
})

$('#id_is_request_for_others').on('change', function(){
	if($(this).is(".checked")){
		$('@pac-input').attr('required', 'required');
		showLocationPickerForm();
	}else{
		$('#pac-input').removeAttr('required');
	}
});



</script>

<script src="{% static 'js/placepicker.js' %}" async defer=""></script>
<script src="https://maps.googleapis.com/maps/api/js?key=kjasdjkasdjkjsdkfjadkjjdcjka"  async defer=""></script>

{% endblock content %}